name: Create Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      pre_release:
        description: 'Pre-release identifier (beta, alpha, rc)'
        required: false
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        id: version
        run: |
          if [ -n "${{ github.event.inputs.pre_release }}" ]; then
            NEW_VERSION=$(npm version ${{ github.event.inputs.version_type }} --preid=${{ github.event.inputs.pre_release }} --no-git-tag-version)
          else
            NEW_VERSION=$(npm version ${{ github.event.inputs.version_type }} --no-git-tag-version)
          fi
          echo "new_version=${NEW_VERSION#v}" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG
        run: |
          cat > CHANGELOG_ENTRY.md << EOF
          ## [${{ steps.version.outputs.new_version }}] - $(date +%Y-%m-%d)
          
          ### Added
          - 
          
          ### Changed
          - 
          
          ### Fixed
          - 
          
          EOF
          
          if [ -f CHANGELOG.md ]; then
            cat CHANGELOG.md >> CHANGELOG_ENTRY.md
            mv CHANGELOG_ENTRY.md CHANGELOG.md
          else
            mv CHANGELOG_ENTRY.md CHANGELOG.md
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: bump version to ${{ steps.version.outputs.new_version }}"
          title: "Release v${{ steps.version.outputs.new_version }}"
          body: |
            ## Release v${{ steps.version.outputs.new_version }}
            
            This PR bumps the version to `${{ steps.version.outputs.new_version }}`.
            
            ### Checklist
            - [ ] Update CHANGELOG.md with release notes
            - [ ] Review changes
            - [ ] Merge to trigger automatic NPM publish
            
            After merging, create a GitHub release to trigger the NPM publish workflow.
          branch: release/v${{ steps.version.outputs.new_version }}
          labels: release